# -*- coding: utf-8 -*-
"""AI_FOR_FARMER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iess1fgACxPmanFxwNXUtsMj2g-4X7Eu
"""

# ============================================================
# 🌾 RURAL AI ASSISTANT — COMPLETE ONE-CELL COLAB VERSION
# ============================================================

# ---------------------------
# 1. INSTALL DEPENDENCIES
# ---------------------------

!pip install -q google-genai faster-whisper edge-tts pillow nest-asyncio python-telegram-bot

# ---------------------------
# 2. IMPORTS
# ---------------------------

import os
import tempfile
import nest_asyncio
import asyncio

from getpass import getpass
from PIL import Image

import torch
from faster_whisper import WhisperModel
from google import genai

import edge_tts

from telegram import (
    Update,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
)
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    CallbackQueryHandler,
    ContextTypes,
    filters,
)

# ---------------------------
# 3. API KEYS
# ---------------------------

GEMINI_API_KEY = getpass("Enter GEMINI_API_KEY: ")
TELEGRAM_BOT_TOKEN = getpass("Enter TELEGRAM_BOT_TOKEN: ")

os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY
os.environ["TELEGRAM_BOT_TOKEN"] = TELEGRAM_BOT_TOKEN

print("✅ API keys loaded.")

# ---------------------------
# 4. GEMINI CLIENT
# ---------------------------

client = genai.Client(
    api_key=GEMINI_API_KEY
)

GEMINI_MODEL = "gemini-3.6-flash"

print("✅ Gemini client initialized.")

# ---------------------------
# 5. SYSTEM PROMPT
# ---------------------------

SYSTEM_PROMPT = """
You are a Rural Public AI Assistant designed for smallholder farmers
and rural ground workers.

You can assist with multiple agricultural crops, including:
tomato, rice, wheat, maize, potato, chilli, brinjal, cucumber,
pulses, fruits, vegetables, and other crops.

The crop mentioned by the farmer may be different in every conversation.
Always identify and respond to the crop mentioned by the farmer.

Do not assume that the farmer is talking about tomato or any other
specific crop.

Your goal is to provide simple, practical and understandable assistance.

CORE PRINCIPLES:

1. Use simple language that a rural user can understand.
2. Avoid unnecessary scientific or technical terminology.
3. Give practical, actionable steps.
4. Prefer familiar local measurements when appropriate.
5. Do not invent facts, pesticide dosages, fertilizer dosages,
   prices, government schemes, or disease treatments.
6. If uncertain, clearly say that you are uncertain.
7. If an uploaded image is unclear, say that the image is insufficient
   for reliable analysis.
8. Never claim a definite crop disease from an image unless the evidence
   is sufficiently clear.
9. For pesticide or chemical advice, recommend following the product
   label and verified agricultural guidance.
10. Keep answers concise enough for a short voice response.

When the farmer mentions a crop:
- Identify the crop explicitly.
- Base the response on that crop.
- Do not replace it with another crop.
- If the crop is unclear, ask the farmer to clarify.

RESPONSE FORMAT:

Crop:
State the crop being discussed.

Problem:
Explain what the farmer may be experiencing.

Possible cause:
Give the most likely possibilities without pretending certainty.

What to do:
Give practical next steps.

What to avoid:
Mention important mistakes or risks.

Warning:
Mention when the farmer should seek expert/local agricultural assistance.
"""

# ---------------------------
# 6. LANGUAGES
# ---------------------------

SUPPORTED_LANGUAGES = {
    "English": "en",
    "Hindi": "hi",
    "Maithili": "mai",
    "Bengali": "bn",
    "Marathi": "mr",
    "Tamil": "ta",
    "Telugu": "te",
    "Kannada": "kn",
    "Gujarati": "gu",
    "Punjabi": "pa",
    "Odia": "or",
    "Malayalam": "ml",
}

TTS_VOICES = {
    "en": "en-IN-NeerjaNeural",
    "hi": "hi-IN-SwaraNeural",
    "bn": "bn-IN-TanishaaNeural",
    "mr": "mr-IN-AarohiNeural",
    "ta": "ta-IN-PallaviNeural",
    "te": "te-IN-ShrutiNeural",
    "kn": "kn-IN-SapnaNeural",
    "gu": "gu-IN-DhwaniNeural",
    "pa": "pa-IN-VaaniNeural",
    "ml": "ml-IN-SobhanaNeural",
    "or": "or-IN-SaamikaNeural",
    # Maithili fallback to Hindi voice
    "mai": "hi-IN-SwaraNeural",
}

# ---------------------------
# 7. WHISPER
# ---------------------------

WHISPER_MODEL_SIZE = "base"

if torch.cuda.is_available():
    whisper_model = WhisperModel(
        WHISPER_MODEL_SIZE,
        device="cuda",
        compute_type="float16",
    )
    print("🚀 Faster-Whisper using GPU.")
else:
    whisper_model = WhisperModel(
        WHISPER_MODEL_SIZE,
        device="cpu",
        compute_type="int8",
    )
    print("💻 Faster-Whisper using CPU.")

print("✅ Whisper loaded.")

# ---------------------------
# 8. SPEECH → TEXT
# ---------------------------

def transcribe_audio(audio_path):
    segments, info = whisper_model.transcribe(
        audio_path,
        beam_size=5,
    )

    text = " ".join(
        segment.text for segment in segments
    )

    return text.strip()

# ---------------------------
# 9. GEMINI TEXT RESPONSE
# ---------------------------

async def generate_farmer_response(
    question: str,
    language_code: str = "en",
) -> str:

    language_name = next(
        (
            name
            for name, code in SUPPORTED_LANGUAGES.items()
            if code == language_code
        ),
        "English",
    )

    prompt = f"""
{SYSTEM_PROMPT}

Respond in {language_name}.

Farmer's question:
{question}
"""

    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
    )

    return response.text.strip()

# ---------------------------
# 10. CROP IMAGE ANALYSIS
# ---------------------------

def analyze_crop_image(
    image_path,
    farmer_question="",
    language_code="en",
):

    image = Image.open(image_path)

    language_name = next(
        (
            name
            for name, code in SUPPORTED_LANGUAGES.items()
            if code == language_code
        ),
        "English",
    )

    prompt = f"""
{SYSTEM_PROMPT}

Respond in {language_name}.

Analyze the uploaded crop image.

Farmer's question:
{farmer_question}

Your task:

1. Identify the crop if it can be identified.
2. Describe what is visibly present.
3. Identify possible disease, pest, nutrient deficiency,
   or other problem only when there is reasonable visual evidence.
4. If the image is insufficient for diagnosis, clearly say so.
5. Give a confidence level: Low, Medium, or High.
6. Give practical next steps.
7. Do not recommend a specific pesticide or chemical dosage
   without verified information.
8. Do not pretend to know something that cannot be determined
   from the image.

Use this format:

Crop:
...

Visible symptoms:
...

Possible problem:
...

Confidence:
...

What to do:
...

What to avoid:
...

Warning:
...
"""

    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=[prompt, image],
    )

    return response.text.strip()

# ---------------------------
# 11. TEXT → SPEECH
# ---------------------------

async def text_to_speech(
    text: str,
    language_code: str = "en",
):

    voice = TTS_VOICES.get(
        language_code,
        TTS_VOICES["en"],
    )

    temp_file = tempfile.NamedTemporaryFile(
        suffix=".mp3",
        delete=False,
    )

    audio_path = temp_file.name
    temp_file.close()

    communicate = edge_tts.Communicate(
        text=text,
        voice=voice,
    )

    await communicate.save(audio_path)

    return audio_path

# ---------------------------
# 12. SEND VOICE RESPONSE
# ---------------------------

async def send_voice_response(
    update: Update,
    text: str,
    language_code: str = "en",
):

    audio_path = None

    try:

        audio_path = await text_to_speech(
            text,
            language_code,
        )

        with open(audio_path, "rb") as audio_file:

            await update.message.reply_voice(
                voice=audio_file,
            )

    except Exception as e:

        print(f"TTS error: {e}")

    finally:

        if audio_path and os.path.exists(audio_path):
            os.remove(audio_path)

# ---------------------------
# 13. /START
# ---------------------------

async def start_command(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):

    message = """
🌾 Welcome to Rural AI Assistant!

I can help you with:

💬 Farming questions
📷 Crop images
🎤 Voice questions
🌱 Crop problem analysis
🌐 Multiple languages

Send me your farming question, crop photo,
or voice message.

Use /language to select your language.
"""

    await update.message.reply_text(message)

# ---------------------------
# 14. TEXT HANDLER
# ---------------------------

async def handle_text(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):

    if not update.message or not update.message.text:
        return

    question = update.message.text.strip()

    if not question:
        return

    await update.message.chat.send_action("typing")

    try:

        language_code = context.user_data.get(
            "language",
            "en",
        )

        answer = await generate_farmer_response(
            question,
            language_code,
        )

        await update.message.reply_text(answer)

    except Exception as e:

        print(f"Text handler error: {e}")

        await update.message.reply_text(
            "Sorry, I couldn't process your question right now."
        )

# ---------------------------
# 15. LANGUAGE COMMAND
# ---------------------------

async def language_command(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):

    keyboard = [
        [
            InlineKeyboardButton(
                "🇬🇧 English",
                callback_data="lang_en",
            ),
            InlineKeyboardButton(
                "🇮🇳 Hindi",
                callback_data="lang_hi",
            ),
        ],
        [
            InlineKeyboardButton(
                "🟢 Maithili",
                callback_data="lang_mai",
            ),
            InlineKeyboardButton(
                "বাংলা Bengali",
                callback_data="lang_bn",
            ),
        ],
        [
            InlineKeyboardButton(
                "मराठी Marathi",
                callback_data="lang_mr",
            ),
            InlineKeyboardButton(
                "தமிழ் Tamil",
                callback_data="lang_ta",
            ),
        ],
        [
            InlineKeyboardButton(
                "తెలుగు Telugu",
                callback_data="lang_te",
            ),
            InlineKeyboardButton(
                "ಕನ್ನಡ Kannada",
                callback_data="lang_kn",
            ),
        ],
        [
            InlineKeyboardButton(
                "ગુજરાતી Gujarati",
                callback_data="lang_gu",
            ),
            InlineKeyboardButton(
                "ਪੰਜਾਬੀ Punjabi",
                callback_data="lang_pa",
            ),
        ],
        [
            InlineKeyboardButton(
                "ଓଡ଼ିଆ Odia",
                callback_data="lang_or",
            ),
            InlineKeyboardButton(
                "മലയാളം Malayalam",
                callback_data="lang_ml",
            ),
        ],
    ]

    await update.message.reply_text(
        "🌐 Select your preferred language:",
        reply_markup=InlineKeyboardMarkup(keyboard),
    )

# ---------------------------
# 16. LANGUAGE CALLBACK
# ---------------------------

async def language_callback(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):

    query = update.callback_query

    await query.answer()

    language_code = query.data.replace(
        "lang_",
        "",
    )

    language_name = next(
        (
            name
            for name, code in SUPPORTED_LANGUAGES.items()
            if code == language_code
        ),
        "English",
    )

    context.user_data["language"] = language_code
    context.user_data["language_name"] = language_name

    await query.edit_message_text(
        f"✅ Language set to {language_name}."
    )

# ---------------------------
# 17. PHOTO HANDLER
# ---------------------------

async def handle_photo(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):

    if not update.message or not update.message.photo:
        return

    await update.message.chat.send_action("typing")

    temp_path = None

    try:

        # Delete previous stored image
        old_image = context.user_data.pop(
            "latest_image",
            None,
        )

        if old_image and os.path.exists(old_image):
            os.remove(old_image)

        photo = update.message.photo[-1]

        telegram_file = await photo.get_file()

        with tempfile.NamedTemporaryFile(
            suffix=".jpg",
            delete=False,
        ) as temp_file:

            temp_path = temp_file.name

        await telegram_file.download_to_drive(
            temp_path
        )

        farmer_question = (
            update.message.caption or ""
        ).strip()

        language_code = context.user_data.get(
            "language",
            "en",
        )

        answer = analyze_crop_image(
            temp_path,
            farmer_question,
            language_code,
        )

        await update.message.reply_text(answer)

        # Keep image for a possible voice follow-up
        context.user_data["latest_image"] = temp_path

        temp_path = None

    except Exception as e:

        print(f"Photo handler error: {e}")

        await update.message.reply_text(
            "Sorry, I couldn't analyze this crop image."
        )

    finally:

        if temp_path and os.path.exists(temp_path):
            os.remove(temp_path)

# ---------------------------
# 18. VOICE HANDLER
# ---------------------------

async def handle_voice(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):

    if not update.message or not update.message.voice:
        return

    await update.message.chat.send_action("typing")

    audio_path = None

    try:

        voice = update.message.voice

        telegram_file = await voice.get_file()

        with tempfile.NamedTemporaryFile(
            suffix=".ogg",
            delete=False,
        ) as temp_file:

            audio_path = temp_file.name

        await telegram_file.download_to_drive(
            audio_path
        )

        question = transcribe_audio(
            audio_path
        )

        if not question:

            await update.message.reply_text(
                "I couldn't understand your voice message. "
                "Please try again."
            )

            return

        language_code = context.user_data.get(
            "language",
            "en",
        )

        image_path = context.user_data.get(
            "latest_image"
        )

        if image_path and os.path.exists(image_path):

            answer = analyze_crop_image(
                image_path,
                farmer_question=question,
                language_code=language_code,
            )

            # Remove image after combined analysis
            context.user_data.pop(
                "latest_image",
                None,
            )

            if os.path.exists(image_path):
                os.remove(image_path)

        else:

            answer = await generate_farmer_response(
                question,
                language_code,
            )

        # Text response
        await update.message.reply_text(answer)

        # Voice response
        await send_voice_response(
            update,
            answer,
            language_code,
        )

    except Exception as e:

        print(f"Voice handler error: {e}")

        await update.message.reply_text(
            "Sorry, I couldn't process your voice message."
        )

    finally:

        if audio_path and os.path.exists(audio_path):
            os.remove(audio_path)

# ---------------------------
# 19. START BOT
# ---------------------------

async def run_bot():

    app = (
        Application
        .builder()
        .token(TELEGRAM_BOT_TOKEN)
        .build()
    )

    # Commands
    app.add_handler(
        CommandHandler(
            "start",
            start_command,
        )
    )

    app.add_handler(
        CommandHandler(
            "language",
            language_command,
        )
    )

    # Language buttons
    app.add_handler(
        CallbackQueryHandler(
            language_callback,
            pattern=r"^lang_",
        )
    )

    # Text
    app.add_handler(
        MessageHandler(
            filters.TEXT & ~filters.COMMAND,
            handle_text,
        )
    )

    # Photos
    app.add_handler(
        MessageHandler(
            filters.PHOTO,
            handle_photo,
        )
    )

    # Voice
    app.add_handler(
        MessageHandler(
            filters.VOICE,
            handle_voice,
        )
    )

    print("==========================================")
    print("🌾 RURAL AI ASSISTANT")
    print("==========================================")
    print("✅ Gemini ready")
    print("✅ Whisper ready")
    print("✅ Vision ready")
    print("✅ Edge-TTS ready")
    print("✅ Telegram handlers registered")
    print("🚀 Bot is starting...")
    print("📱 Open Telegram and send /start")
    print("==========================================")

    await app.initialize()
    await app.start()
    await app.updater.start_polling()

    print("🟢 BOT IS RUNNING!")

    # Keep Colab cell alive
    while True:
        await asyncio.sleep(3600)

# ---------------------------
# 20. START
# ---------------------------

nest_asyncio.apply()

await run_bot()